import {auth} from "@clerk/nextjs/server";import {db} from "./db";import type {CreateListingInput,UpdateListingInput} from "./marketplace";
async function requireUserId(){const{userId}=await auth();if(!userId)throw new Error("Unauthorized");return userId}
const publicCategories=["sell","trade","free","services","goods"];
function normalize<T extends {category:string}>(row:T){return {...row,category:row.category==="goods"?"sell":row.category}}
export async function listActiveMarketplaceListings(category?:string,query?:string){const categoryWhere=category==="sell"?{category:{in:["sell","goods"]}}:category?{category}:{category:{in:publicCategories}};const q=query?.trim();const searchWhere=q?{OR:[{title:{contains:q,mode:"insensitive" as const}},{description:{contains:q,mode:"insensitive" as const}}]}:{};const rows=await db.marketplaceListing.findMany({where:{status:"active",...categoryWhere,...searchWhere},select:{id:true,title:true,description:true,category:true,priceCents:true,createdAt:true,photos:{orderBy:{sortOrder:"asc"},select:{url:true},take:1},availability:{where:{endsAt:{gt:new Date()}},select:{id:true},take:1}},orderBy:{createdAt:"desc"},take:100});return rows.map(normalize)}
export async function findPublicListing(id:string){const row=await db.marketplaceListing.findFirst({where:{id,status:"active",category:{in:publicCategories}},select:{id:true,title:true,description:true,category:true,priceCents:true,createdAt:true,photos:{orderBy:{sortOrder:"asc"},select:{id:true,url:true}},availability:{where:{endsAt:{gt:new Date()}},select:{id:true},take:1}}});return row?normalize(row):null}
export async function listOwnedListings(){const userId=await requireUserId();const rows=await db.marketplaceListing.findMany({where:{ownerId:userId},include:{photos:{orderBy:{sortOrder:"asc"}}},orderBy:{createdAt:"desc"}});return rows.map(normalize)}
export async function findOwnedListing(id:string){const userId=await requireUserId();const row=await db.marketplaceListing.findFirst({where:{id,ownerId:userId},include:{photos:{orderBy:{sortOrder:"asc"}},availability:{orderBy:{startsAt:"asc"}}}});return row?normalize(row):null}
export async function createOwnedListing(input:CreateListingInput){const userId=await requireUserId();return db.marketplaceListing.create({data:{ownerId:userId,title:input.title,description:input.description,category:input.category,priceCents:input.priceCents}})}
export async function updateOwnedListing(id:string,input:UpdateListingInput){const userId=await requireUserId();const existing=await db.marketplaceListing.findFirst({where:{id,ownerId:userId},select:{id:true}});if(!existing)return null;return db.marketplaceListing.update({where:{id:existing.id},data:input})}
export async function deleteOwnedListing(id:string){const userId=await requireUserId();const result=await db.marketplaceListing.deleteMany({where:{id,ownerId:userId}});return result.count===1}
